/**
 * Site config. Regenerated by scripts/build_site_config.py after calendar/form/sheet build.
 * Override values in your runtime by editing this file manually if needed.
 */
window.SITE_CONFIG = {
  calendarId: "37da5bbc7e2cdf4182b8f40910425a12d8acfdd2f16add300e1a87aac970d72c@group.calendar.google.com",
  calendarTimezone: "America/Panama",

  // Subscribe via Google Calendar UI (one-tap on desktop, account-required)
  calendarSubscribeUrl: "https://calendar.google.com/calendar/u/0/r?cid=37da5bbc7e2cdf4182b8f40910425a12d8acfdd2f16add300e1a87aac970d72c%40group.calendar.google.com",

  // ICS feed (universal subscribe URL — works for Apple Cal, Outlook, anything)
  calendarIcsUrl: "https://calendar.google.com/calendar/ical/37da5bbc7e2cdf4182b8f40910425a12d8acfdd2f16add300e1a87aac970d72c%40group.calendar.google.com/public/basic.ics",

  // Embedded calendar view (for the optional <iframe> fallback)
  calendarEmbedUrl: "https://calendar.google.com/calendar/embed?src=37da5bbc7e2cdf4182b8f40910425a12d8acfdd2f16add300e1a87aac970d72c%40group.calendar.google.com&ctz=America/Panama",

  // CORS proxy for the ICS feed (Google Calendar doesn't send CORS headers).
  // Using corsproxy.io — public free proxy. If it goes down, see app.js fallback.
  icsProxyUrl: "https://corsproxy.io/?",

  // Flight form (responder URL — anyone with link can submit)
  flightFormUrl: "https://docs.google.com/forms/d/e/1FAIpQLScSzFBjgHNgK_SMrD88BPlZSx5SCWpS657V8OsD9o4moyUdGQ/viewform",

  // Flight sheet — populated after manual Form-to-Sheet link step
  // Format: published-to-web URL of the sheet (set to null until linked)
  flightSheetEmbedUrl: "https://docs.google.com/spreadsheets/d/1rYZYlRqDQBzsqlc53tlYq0me39G_yVToUwQrz4r19MM/htmlembed?gid=478115035&widget=true&headers=false&chrome=false",
  flightSheetViewUrl: "https://docs.google.com/spreadsheets/d/1rYZYlRqDQBzsqlc53tlYq0me39G_yVToUwQrz4r19MM/edit#gid=478115035",
};
